apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: devopstraining
  name: devopstraining
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopstraining
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devopstraining
    spec:
      imagePullSecrets:
        - name: mytrainregistrykey
      containers:
      - image: darivala/mydocimg:15
        name: devopstraining-image
        ports:
        - containerPort: 8080
          name: http
        resources: {}
status: {}
